---
- name: Create 20 users on Azure Ubuntu VM
  hosts: ubuntu_vm
  become: yes
  vars_files:
    - users.yml

  vars:
    default_password_hash: "$6$17V87TnQjH5hyrx/$xJk23bpZPfh7pvav3zJF6NjFXcLWFb4n0tmPOEIViqU090m18H7PfbT3mEyI7f9u1pgurHfGIMe6KjrG8NY7."

  tasks:

    - name: Ensure users exist and set password always
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        create_home: yes
        password: "{{ default_password_hash }}"
        update_password: always   # << FIX
      loop: "{{ users }}"
